name: 4d_gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.11
  - pip=23.3.1
  - pytorch=2.1.0
  - pytorch-cuda=12.4
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - plyfile=0.8.1
  - colmap
  - pip:
    - tqdm==4.66.1
    - torchmetrics==1.2.0
    - imagesize==1.4.1
    - kornia==0.7.0
    - omegaconf==2.3.0
    - ./simple-knn
    - ./pointops2
