name: 4d_gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=2.1.0
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - colmap
  - pip:
    - tqdm==4.66.1
    - torchmetrics==0.11.4
    - imagesize==1.4.1
    - kornia==0.6.12
    - omegaconf==2.3.0
    - ./simple-knn
    - ./pointops2
    
